CREATE TABLE address (id INTEGER NOT NULL, city VARCHAR(255), person_id BIGINT, street VARCHAR(255));
CREATE TABLE person (id BIGINT NOT NULL, name VARCHAR(255));
CREATE TABLE users (id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, age INTEGER, active TINYINT);
CREATE TABLE user (id INTEGER NOT NULL, age INTEGER NOT NULL, active BIT, name VARCHAR(255));
DROP TABLE department;
DROP TABLE students;